spring.application.name=SpringBoot2

# (SpringBoot Actuators)Expose all actuator endpoints
management.endpoints.web.exposure.include=*

# (SpringBoot Actuators)Show health details
management.endpoint.health.show-details=always

# config
employee.company-name=OpenAI Technologies
employee.location=Mumbai