###  These application.properties is good for small project as project grows their will be
###  hundreds of properties -> Becomes difficult to read ; so we use yaml (Ain't Markup Language).
### You can use these or application.yml or application.properties
#
##1 Application Name
#spring.application.name=SpringBoot2
#
## (SpringBoot Profile)
#
#
## (SpringBoot Actuators)Expose all actuator endpoints
#management.endpoints.web.exposure.include=*
#
## (SpringBoot Actuators)Show health details
#management.endpoint.health.show-details=always
#
## Real Enterprise config :- instead if @Value we use @ConfigurationProperties
#employee.company-name=OpenAI Technologies
#employee.location=Mumbai
#employee.department=IT
#employee.email=support@openai.com
#employee.phone=1234567890
